Vagrant.configure("2") do |config|
    config.vm.box = "gce"
    config.vm.provider :google do |google, override|
      google.google_project_id = "PROJECT_ID"
      google.google_client_email = "PROJECT_ID_SERVICE_ACCOUNT@developer.gserviceaccount.com"
      google.google_json_key_location = "~/path/to/gcloud.json"
      # Provide an instance name
      google.name = "devel"
      # Specify the zone where your instance will be located
      google.zone = "asia-east1-c"
      # Specify the machine type you would like to use
      google.machine_type = "n1-standard-2"
      # Specify the image that will be used
      google.image = "ubuntu-1404-trusty-v20150901a"
      #provide the SSH user name and location of private key
      override.ssh.username = "chao"
      override.ssh.private_key_path = "~/.ssh/id_rsa"
    end
  end